"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
"""
from collections import Counter


def search(string_s, string_t):
    count_s = Counter(string_s)
    count_t = Counter(string_t)
    print(count_s, count_t)

    for char in count_t:
        if count_t[char] != count_s.get(char, 0):
            return char


print(search("abcd", "abcde"))